apiVersion: v1
kind: Service
metadata:
    name: user-interface
    labels:
        app: user-interface
spec:
    ports:
        - port: 80
          targetPort: 8080
    selector:
        app: user-interface
        tier: app
    type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata: 
    name: user-interface
    labels: 
      app: user-interface
spec:
    minReadySeconds: 0
    replicas: 1
    selector:
        matchLabels:
            app: user-interface
            tier: app
    template: 
        metadata:
            labels:
                app: user-interface
                tier: app
        spec:
            containers:
                - name: app-clip
                  image: zigakern/user_interface:v0.1.8
                  env:
                    - name: KUMULUZEE_CONFIG_ETCD_HOSTS
                      value: http://etcd:2379
                    - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
                      value: http://etcd:2379
                  ports:
                    - containerPort: 8080
                      name: app
                      protocol: TCP
                  livenessProbe:
                    httpGet:
                      path: /health
                      port: 8080
                    initialDelaySeconds: 60
                    periodSeconds: 5