kumuluzee:
  name: user_interface
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  config:
    etcd:
      hosts: http://192.168.99.100:2379
  discovery:
      etcd:
        hosts: http://192.168.99.100:2379
  logs:
        config-file:
          '<?xml version="1.0" encoding="UTF-8"?>
           <Configuration name="clip-logging">
               <Appenders>
                   <Console name="console" target="SYSTEM_OUT">
                       <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                   </Console>
                   <Socket name="logstash" host="a74a2a0e-e621-4208-84ae-7662068886fb-ls.logit.io" port="22776" protocol="tcp">
                       <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                   </Socket>
               </Appenders>
               <Loggers>
                   <!-- Default logger -->
                   <Root level="all">
                        <AppenderRef ref="console" level="info"/>
                        <AppenderRef ref="logstash" level="info"/>
                    </Root>
               </Loggers>
           </Configuration>'
  health:
        logs:
              enabled: true
              level: FINE
              period-s: 60
        checks:
          http-health-check:
                  connection-url: http://localhost:8080/
  metrics:
      servlet:
        enabled: true
        mapping: /metrics
      web-instrumentation:
        - name: webEndpoint
          url-pattern: /*
rest-properties:
  external-dependencies:
    clip-service:
      url: http://192.168.99.100:8081/v1
